# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'grokHTMLAndDownloads-htmlAndDownloads_4.0' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'HTMLReader'
  pod 'Alamofire'
  pod 'SwiftyJSON'    

  # Pods for grokHTMLAndDownloads-htmlAndDownloads_4.0

  target 'grokHTMLAndDownloads-htmlAndDownloads_4.0Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'grokHTMLAndDownloads-htmlAndDownloads_4.0UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
